language: python

python:
  - "3.6"

install:
  # Install dependencies
  - pip install flake8 urlquick polib mock htmlement colorama requests
  - git clone https://github.com/Catch-up-TV-and-More/catchuptvandmore-test ../simul

env:
  - JOB=flake
  - JOB=simul_root
  - JOB=simul_replay
  - JOB=simul_replay_country
  - JOB=simul_replay_french

script:
  - if [ $JOB == 'flake' ]; then flake8 .; fi
  - if [ $JOB == 'simul_root' ]; then cd ../simul && ./main.py -c configs/0_open_root_and_exit.json; fi
  - if [ $JOB == 'simul_replay' ]; then cd ../simul && ./main.py -c configs/1_open_replay_menu_and_exit.json; fi
  - if [ $JOB == 'simul_replay_country' ]; then cd ../simul && ./main.py -c configs/2_open_each_replay_country_root_menu_and_exit.json; fi
  - if [ $JOB == 'simul_replay_french' ]; then cd ../simul && ./main.py -c configs/3_open_each_french_replay_channel_menu_and_exit.json; fi


notifications:
  email:
    on_success: change
    on_failure: always
