language: python

python:
  - "3.6"

install:
  # Install dependencies
  - "pip install flake8 urlquick polib mock htmlement colorama requests"

script:
  # Check PEP8 and syntax error in python files
  - flake8 .

  # Git clone catchuptvandmore-test framework
  - cd ..
  - git clone https://github.com/Catch-up-TV-and-More/catchuptvandmore-test
  - cd catchuptvandmore-test

  # Apply different exploration config
  - ./main.py -c configs/0_open_root_and_exit.json
  - ./main.py -c configs/1_open_replay_menu_and_exit.json
  - ./main.py -c configs/2_open_each_replay_country_root_menu_and_exit.json
  - ./main.py -c configs/3_open_each_french_replay_channel_menu_and_exit.json

notifications:
  email:
    on_success: change
    on_failure: always
