language: python

python:
  - "3.6"

install:
  # Install dependencies
  - pip install flake8 urlquick polib mock htmlement colorama requests
  - git clone https://github.com/Catch-up-TV-and-More/catchuptvandmore-test ../simul

env:
  - JOB=flake
  # - JOB=simul_root
  # - JOB=simul_replay
  - JOB=simul_replay_country
  # - JOB=simul_replay_french
  - JOB=simul_replay_french_depth

script:
  - if [ $JOB == 'flake' ]; then flake8 . 2>&1|tee ${JOB}.log; fi
  # - if [ $JOB == 'simul_root' ]; then cd ../simul && ./main.py -c configs/0_open_root_and_exit.json 2>&1|tee "${JOB}.log"; fi
  # - if [ $JOB == 'simul_replay' ]; then cd ../simul && ./main.py -c configs/1_open_replay_menu_and_exit.json 2>&1|tee "${JOB}.log"; fi
  - if [ $JOB == 'simul_replay_country' ]; then cd ../simul && ./main.py -c configs/2_open_each_replay_country_root_menu_and_exit.json 2>&1|tee ${JOB}.log; fi
  # - if [ $JOB == 'simul_replay_french' ]; then cd ../simul && ./main.py -c configs/3_open_each_french_replay_channel_menu_and_exit.json 2>&1|tee "${JOB}.log"; fi
  - if [ $JOB == 'simul_replay_french_depth' ]; then cd ../simul && ./main.py -c configs/4_open_each_french_replay_channel_in_depth.json 2>&1|tee ${JOB}.log; fi

# In case of failure we upload the log in print the log URL
after_failure:
  - curl -L https://github.com/Catch-up-TV-and-More/catchuptvandmore-test/raw/master/utils/haste > haste_${JOB} && chmod 755 haste_${JOB} && echo "* Complete log file can be found here:" && ./haste_${JOB} ${JOB}.log

notifications:
  email:
    on_success: change
    on_failure: always
